schema: .\\src\\schema\\food_system_indicators.yaml

target_class: 'indicator'
data_sources:
  - CsvLoader:
      source: .\\data\\indicators.csv      

## target_class: 'indicator datapoint'
##//data_sources:
##  - CsvLoader:
##      source: .\\data\\indicator datapoints.csv